//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Manager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Add_to_cart
    {
        public string Name { get; set; }
        public string Price { get; set; }
        public string picture { get; set; }
    }
}
