//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Web;

namespace WebApplication3.Manager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Addproduct
    {
        public int productid { get; set; }
        public string productname { get; set; }
        public string productprice { get; set; }
        public string productimage { get; set; }

        public HttpPostedFileBase Image { get; set; }
    }
}
